@startuml

skinparam shadowing false
skinparam packageStyle rectangle

skinparam class {
  BackgroundColor White
  BorderThickness 3
  ArrowThickness 2
  ArrowColor Maroon
  BorderColor Maroon
  FontColor Maroon
}

package objectForm {

class Switch
    interface Switchable {
        + turn(boolean)
      }

    Switch -> Switchable

    class Light {
        + turnOn()
        + turnOff()
    }

    class LightAdapter {
        + setLight(light)
    }

    Switchable <|-- LightAdapter
    Light <- LightAdapter
}

package classForm {

class Switch2 as "Switch"
    interface Switchable2 as "Switchable" {
        + turn(boolean)
      }

    Switch2 -> Switchable2

    class Light2 as "Light" {
        + turnOn()
        + turnOff()
    }

    class LightAdapter2 as "LightAdapter"

    Switchable2 <|-- LightAdapter2
    Light2 <|- LightAdapter2
}
@enduml
