@startuml

skinparam linetype ortho

title Strategy Pattern

class FTP {
    Protocol pp
    sendFile(File file)
}

interface  PacketProtocol {
    sendPacket(Packet packet)
}

class XModemPP implements PacketProtocol {
    sendPacket(Packet packet)
}

class YModemPP implements PacketProtocol {
    sendPacket(Packet packet)
}

FTP -> PacketProtocol

@enduml
